config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "top#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    sessions: "users/sessions"
  }

 get "/index/:genre", to: "items#index"

 resources :users, only: [:show]
 resources :posts
 resources :memos
 devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :post_genres, dependent: :destroy
  has_many :posts, through: :post_genres, dependent: :destroy
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user, optional: true
  validates :title, presence: true, length: { maximum: 30 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :post_genres, dependent: :destroy
  has_many :genres, through: :post_genres, dependent: :destroy

  validates :product, presence: true, length: { maximum: 30 }
  validates :start_time, presence: true
end

app/models/post_genre.rb
class PostGenre < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post
  belongs_to :genre
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :memos, dependent: :destroy
  has_many :post_genres, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
   end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
    root_path
    end

     def after_sign_out_path_for(resource)
    root_path
     end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

before_action :set_memo, only: %i[edit update destroy]
before_action :move_to_signed_in, except: [:top]

def index
  @memos = Memo.where(user_id: current_user.id)
  @memo = Memo.new
end

def create
  @memo = Memo.new(memo_params)
  if @memo.save
    redirect_to memos_path, notice: "追加しました"
  else
    flash.now[:alert] = "追加に失敗しました"
    redirect_to memos_path
  end
end

def edit
   @memo = Memo.find(params[:id])
end

def update
  if @memo.update(memo_params)
    redirect_to memos_path, notice: "変更しました"
  else
    flash.now[:alert] = "変更に失敗しました"
    render :edit
  end
end

def destroy
  @memo = Memo.find(params[:id])
  @memo.destroy
  redirect_to memos_path, alert: "削除しました"
end

private

 def set_memo
  @memo = Memo.find(params[:id])
 end

 def memo_params
  params.require(:memo).permit(:title, :content).merge(user_id: current_user.id)
 end

 def move_to_signed_in
  unless user_signed_in?
    #サインインしていないユーザーはログインページが表示される
  redirect_to "/users/sign_in"
  end
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: %i[edit update destroy]
  before_action :move_to_signed_in, except: [:top]

  def index
    if params[:from_memo].present?
      # 在庫の追加
    Post.create(product: params[:title], memo: params[:content], start_time: Date.today, user_id: current_user.id)
    end
    @genres = Genre.all
    @posts = params[:name].present? ? Genre.find(params[:name]).posts.where(user_id: current_user.id) : Post.where(user_id: current_user.id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
    @post_genre = PostGenre.create(post_id: @post.id, genre_id: params[:post][:genre_ids], user_id: @post.user_id)

      redirect_to posts_path, notice: "#{@post.product}を追加しました"
    else
      flash.now[:alert] = "追加に失敗しました"
      render :new
    end
  end

  def edit
  end

  def update
    @post = Post.find(params[:id])
    @post.post_genres.destroy_all
     PostGenre.create(post_id: @post.id, genre_id: params[:post][:genre_ids], user_id: @post.user_id)
    if @post.update(post_params)
      redirect_to posts_path, notice: "#{@post.product}を更新しました"
    else
      flash.now[:alert] = "更新しました"
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, alert: "#{@post.product}を削除しました"
  end

  def show
    #byebug
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:product, :memo, :start_time,  user_id: @current_user.id)
  end

  def move_to_signed_in
    unless user_signed_in?
      #サインインしていないユーザーはログインページが表示される
      redirect_to "/users/sign_in"
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]
  

  def ensure_normal_user
    if resource.email == "guest@example.com"
      redirect_to root_path,alert: "ゲストユーザーの更新・削除はできません。"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    # ゲストアカウントでログイン
    sign_in User.guest
    #トップページへリダイレクト
    redirect_to posts_path, notice: "ゲストユーザーとしてログインしました。"
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.html.erb
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger" role="alert">
      <a href="#" class="close" data-dismiss="alert">×</a>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
  <i class="fa-solid fa-cart-shopping"></i>
  <%= link_to "FOOD-STORAGE-CONTAINER", root_path, class: "navbar-brand text-dark" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav">
  <i class="fa-solid fa-magnifying-glass"></i>
      <%= link_to "在庫一覧", posts_path, class: "nav-item nav-link active" %>
      <i class="fa-solid fa-bag-shopping"></i>
      <%= link_to "買い物リスト", memos_path, class: "nav-item nav-link active" %>
    </ul>
    <% if user_signed_in? %>
      <%# ログイン時 %>
      <ul class="navbar-nav ml-auto">
          <i class="fa-solid fa-check"></i>
        <%= link_to "アカウント編集", edit_user_registration_path, class: "nav-item nav-link active" %>
          <i class="fas fa-sign-out-alt"></i>
        <%= link_to "ログアウト", destroy_user_session_path, class: "nav-item nav-link active", method: :delete, data: { confirm: "ログアウトしますか？" } %>
      </ul>
    <% else %>
      <%# 非ログイン時 %>
      <ul class="navbar-nav ml-auto">
      　   <i class="fas fa-user-plus"></i>
        <%= link_to "新規登録", new_user_registration_path, class: "nav-item nav-link active" %>
          <i class="fas fa-sign-in-alt"></i>
        <%= link_to "ログイン", new_user_session_path, class: "nav-item nav-link active" %>
          <i class="fa-solid fa-circle-user"></i>
        <%= link_to "ゲストログイン(閲覧用)", users_guest_sign_in_path, method: :post, class: "nav-item nav-link active" %>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FOOD-STORAGE-CONTAINER</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
　　<script src="https://kit.fontawesome.com/d6a6b00c4f.js" crossorigin="anonymous"></script>
    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <header>
      <%= render "layouts/header" %>
    </header>
    <main>
      <%= render "layouts/flash" %>
      <div class="container-fluid py-4 <%= devise_controller? ? 'mw-md' : 'mw-xl' %>">
      <div class="base-container" >
      <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/memos/edit.html.erb
<h1>編集</h1>
<%= form_with model: @memo, local: true do |form| %>
 <div>
   <%= form.label :title, "商品名" %>
   <%= form.text_field :title %>
 </div>
 <div>
   <%= form.label :content, "備考" %>
   <%= form.text_field :content %>
  </div>
  <div>
   <%= form.submit "更新", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/memos/index.html.erb
<div class="memos-container">
  <div class="split-item split-left">
   <div class="split-left_inner">
    <h2>リスト追加</h2>
    <%= form_with model: @memo, local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div>
    <%= form.submit "追加" %>
  </div>
<% end %>
  </div>
</div>
<div class="split-item split-right">
  <div class="split-right_inner">
   <h2 class="text-center">買い物リスト</h2>
   <table class="table mt-4">
     <thead>
       <tr>
         <th scope="col">商品</th>
         <th scope="col">備考</th>
         <th scope="col"></th>
         <th scope="col"></th>
       </tr>
     <thead>
     <tbody>
       <% @memos.each do |memo| %>
         <tr>
           <td><%= link_to "#{memo.title}", edit_memo_path(memo) %></td>
           <td><%= memo.content %></td>
           <td class="botton">
             <%= link_to posts_path(from_memo: true, title: memo.title, content: memo.content), class: "btn btn-outline-primary" do %>
               <span class="d-none d-md-inline">在庫に追加</span>
             <% end %>
           </td>
           <td class="botton">
             <%= link_to memo, method: :delete, class: "btn btn-outline-danger" do %>
              <i class="far fa-trash-alt"></i> <span class="d-none d-md-inline"> 削除</span>
             <% end %>
           </td>
         </tr>
      <% end %>
    </tbody>
  </table>
  </div>
 </div>
</div>

app/views/posts/_deadline.html.erb
<% if post.start_time - Date.today >= 0 %>
  <p>あと <%= (post.start_time - Date.today).to_i%> 日</p>
<% else %>
  <p>期限が過ぎています</p>
<% end %>

app/views/posts/_form.html.erb
<%# 更新ページ %>
<%= render "layouts/error_messages" %>
<%= form_with model: @post, local: true do |form| %>
  <div class="collection_radio_buttons">
    <%#= form.collection_check_boxes(:genre_ids, Genre.all, :id, :name) do |genre| %>
      <!--<div class='form-check'>-->
        <%#= genre.check_box %>
        <%#= genre.label %>
      <!--</div>-->
    <%# end %>
  <%# チェックボックスからラジオボタンに変更してチェック済みオプションをつける %>
   <% if @post.post_genres.size > 0 %>
  <%# ラジオボタンのオプションをつける do |b|をつけて、</div>で囲む。横並びとラベルとボタンをひとくくりにする %>
   <%= form.collection_radio_buttons(:genre_ids, Genre.all, :id, :name,{ checked:  @post.post_genres.first.genre_id }) do |b| %>
   <div>
   <%= b.radio_button %>
   <%= b.label %>
   </div>
   <% end %>
   <% else %>
   <%= form.collection_radio_buttons(:genre_ids, Genre.all, :id, :name) do |b| %>
   <div>
   <%= b.radio_button %>
   <%= b.label %>
   </div>
   <% end %>
   <% end %>
  </div>
  <br>
  <div class="product">
    <div class="form-tag"><%= form.label :product %></div>
    <%= form.text_field :product %>
  </div>
  <br>
  <div class="start_time">
    <div class="form-tag"><%= form.label :start_time %></div>
    <%= form.date_field :start_time %>
  </div>
  <br>
  <div class="memo">
    <div class="form-tag"><%= form.label :memo %></div>
    <%= form.text_field :memo %>
  </div>
  <br>
  <div class="d-grid gap-2 col-6">
    <%= form.submit button_value, class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="text-page">
<div class="form-group">
  <%# rowで設定すると真ん中に設定されるcol-md-(数字)でサイズが変わる（22~23セット）%>
      <div class="row">
      <div class="col-md-2 mx-auto">
 <h1>更新</h1>
 <%= render "form", button_value: "更新" %>
</div>
</div>
</div>

app/views/posts/index.html.erb
<div class="page">
  <h1 class="text-center">在庫一覧</h1>
  <%= link_to new_post_path, class: "btn btn-outline-success mb5 btn-new" do %>
    <i class="fas fa-pen-fancy"></i> <span class="d-none d-md-inline"> 商品追加</span>
  <% end %>
  <%= form_tag posts_path, method: :get, class: 'boards__searchForm' do %>
    <% @genres.each do |genre| %>
      <%= link_to genre.name, posts_path(name: genre.id), class: "btn btn-outline-primary" %>
    <% end %>
    <%= link_to "全商品", posts_path, class: "btn btn-outline-primary"  %>
  <% end %>
   <table class="table table-striped table-striped mt-4">
    <thead>
     <tr>
        <th scope="col">商品名</th>
        <th scope="col">ジャンル</th>
        <th scope="col">期限</th>
        <th scope="col">残り日数</th>
        <th scope="col">備考</th>
        <th></th>
     </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td class="break-word"><%= link_to "#{post.product}", edit_post_path(post) %></td>
          <% post.genres.each do |genre| %>
            <td class="break-word"><%= genre.name %></td>
          <% end %>
          <td class="break-word"><%= post.start_time.strftime("%Y/%m/%d") %></td>
          <td class="break-word">
            <% if post.start_time - Date.today > 0 %>
              <span>あと <%= (post.start_time - Date.today).to_i %> 日</span>
            <% elsif post.start_time - Date.today == 0 %>
              <span class="warning">今日まで</span>
            <% else %>
              <span class="alort">期限切れ</span>
            <% end %></td>
          <td class="break-word"><%= post.memo %></td>
          <td class="text-nowrap">
            <%= link_to post, method: :delete, data: { confirm: "削除しますか?" }, class: "btn btn-outline-danger" do %>
              <i class="far fa-trash-alt"></i> <span class="d-none d-md-inline"> 削除</span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <h2 class="text-center">商品期限カレンダー</h2>
  <div class="col-md-12">
    <%= month_calendar events: @posts do |date, posts| %>
      <%= date.day %>
      <% posts.each do |post| %>
        <div>
          <%= link_to post.product, edit_post_path(post) %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
</div>
</div>
</div>

app/views/posts/new.html.erb
<div class="text-page">
<div class="form-group">
  <%# rowで設定すると真ん中に設定されるcol-md-(数字)でサイズが変わる（22~23セット）%>
      <div class="row">
      <div class="col-md-2 mx-auto">
  <h1>商品追加</h1>
   <div class="md-3 mx-auto">
  <%= render "form", button_value: "投稿" %>
   </div>
</div>
</div>
</div>

app/views/top/index.html.erb
<div class= "mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">


<h1><strong>Hey! <i class="fa-solid fa-cart-shopping"></i>FOOD-STORAGE-CONTAINER</strong></h1>
  <p>環境省のデータから令和3年度は532万トンのうち家庭系は244万トンもの食品ロスが出ています。<br>
  そして「NEP Food Waste Index Report 2021」での2021年版の食品ロスランキングでは日本は14位で800万トンもの食品を捨てている現状があります。</p>
  <p>買っていたものを忘れ食材が悪くなったので捨ててしまうのは実にお金や食材がもったいない!</p>
  <p>ならば、買ってきたものを忘れないよう管理しよう！！</p>
  <div class= "btn-wrapper col-4 mx-auto">
    <div class="row">
      <%= link_to "新規登録", new_user_registration_path, class: "btn btn-primary btn-block mb-4" %>
    </div>
    <div class="row">
      <%= link_to "ログイン", new_user_session_path, class: "btn btn-info btn-block mb-4" %>
    </div>
    <div class="row">
      <%= link_to "ゲストログイン(閲覧用)", users_guest_sign_in_path, method: :post, class: "btn btn-secondary  btn-block mb-4" %>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase) %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t(".sign_in"), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t(".sign_up"), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t(".forgot_your_password"), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t('.sign_in_with_provider', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>